### PR TITLE
Remove Helpin' Red from LEARNING.md

### PR DESCRIPTION
**Pull request by BNAndras**
Helpin' Red's certificate expired 543 days ago so I'd like to remove it to be safe and substitute in Red By Example. It's unfortunate because Helpin' Red is a good resource otherwise. Thoughts?

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
I think that is a good idea. You could also link to the wayback machine for when you trusted it.

**Review by loziniak — APPROVED** [review]
For me expired certificate is not a sign of malice, but **stagnation**. Which is a fact in Red's community. It's more possible, that the owner just forgot to update cert, than the site was hacked. I'll post on Red's Matrix channel to get this sorted out. For now I'm ok with the change.

**Comment by BNAndras** [comment]
Yeah, I worded that poorly, but I didn’t want to spook the student by sending them to a site where the browser may warn them not to enter. I’d like to keep the link so we can wait a little while . If the cert is fixed, we can keep the link and still add Red by Example.

**Comment by loziniak** [comment]
I like @kotp 's idea of giving a link to archive.org: http://web.archive.org/web/20220116214527/https://helpin.red/

**Comment by loziniak** [comment]
Also, would be nice to have some meaningful commit message, with reason of such change.

**Comment by BNAndras** [comment]
Sounds good. I'll update this early next week.

**Comment by BNAndras** [comment]
The certificate for https://helpin.red/ has been renewed so I'm going to close the PR.

**Pull request closed without merging**
