### PR TITLE
Update bin/fetch-configlet script

### PR DESCRIPTION
**Pull request by loziniak**
The script has been tweaked to work better across all platforms.

### CODE REVIEW

**Comment by loziniak** [comment]
@kytrinyx  Is this intended to merge? There's no PR, should I just merge the branch?

**Comment by loziniak** [comment]
This file has been changed also in f20859a61f8 .

**Comment by ErikSchierboom** [comment]
@loziniak I think this can be merged as the other PR uses the source of truth

**Comment by loziniak** [comment]
I'd appreciate if somebody working on configlet could resolve the conflicts. That's a big task for me, perhaps someone can do it in 5 minutes. @exercism/maintainers-admin

**Comment by loziniak** [comment]
Seems like I should rather leave existing version, from latest *main*, which is the same as [current configlet repo version](https://github.com/exercism/configlet/blob/main/scripts/fetch-configlet).

**Comment by loziniak** [comment]
I don't understand, what do you mean by "source of truth"?

**Comment by ErikSchierboom** [comment]
With merged, I meant closed 🤦 This PR is superfluous

**Pull request closed without merging**
