### PR TITLE
Initial implementation of leap exercise

### LINKED ISSUE #98: Implement leap exercise
I'd like to provide the initial implementation of the leap exercise.

### PR DESCRIPTION
**Pull request by BNAndras**
closes #98

### CODE REVIEW

**Comment by BNAndras** [comment]
@loziniak, can I get a review / merge? I have other exercises I can port if you're available.

**Comment by BNAndras** [comment]
Don't worry about it. Thanks for the offer, but already maintain three tracks and contribute heavily to a fourth so I've got my hands full. :)

I don't want to crowd you though. If you want additional exercises ported, I can do that and leave them for your review whenever you're up for it. If you don't, that's fine too.

**Comment by loziniak** [comment]
Ok, understood. What do you think about these changes I suggested? I'll apply them if you won't do it yourself, ok?

**Comment by loziniak** [comment]
Additional exercises would be great of course, I'll happily review anything you contribute :-) Also, if you have any suggestions to new exercise creation process, feel free to express that in form of issues. Your input as maintainer on other tracks is extremely valuable.

**Comment by BNAndras** [comment]
I don't see the two comments. Were they part of a review?

**Comment by loziniak** [comment]
Yes, I think so. I hope I didn't mess something up so they are not visible to you:

obraz

**Pull request merged**
