### PR TITLE
fix: remove files configuration

### PR DESCRIPTION
**Pull request by loziniak**
it's in track's config.json now.

### CODE REVIEW

**Review by ErikSchierboom — CHANGES_REQUESTED** [review]
The `files` property must still be there. The `files` property in the track's `config.json` is just there to allow `configlet` to help populate these files for exercise `.meta/config.json` files.

See https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#files and https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-metaconfigjson.

**Comment by loziniak** [comment]
Seems redundant to me. Is this by design? Why is it needed?

**Comment by ErikSchierboom** [comment]
> Seems redundant to me. Is this by design? Why is it needed?

It is by design and there are several reasons for this: 

- Tracks are allowed to diverge from the defaults, they don't have to use the pattern specified in the track's config.json files
- We want the website to not have to do any preprocessing on determine the exercise files
- Track tooling works on exercises and will not have access to the track config.json file

**Comment by loziniak** [comment]
I think I'll remove `files` key from track's *config.json* then.

**Comment by ErikSchierboom** [comment]
> I think I'll remove files key from track's config.json then.

You can, but if you keep it in there. at some point you'll be able to run `configlet sync --filepaths` to automatically populate the values. Your choice 🤷

**Comment by loziniak** [comment]
I probably don't know all the reasons behind it, but I'd just provide track tooling with track's *config.json*, rather than creating a tool to populate redundant information.

**Comment by ErikSchierboom** [comment]
Well, I listed the reasons above :) But your choice!

**Comment by loziniak** [comment]
Sure! But these reasons can be seen as decisions, that have their own reasons and I don't want to dig that deep, probably it's too late for discussions like that so I just accept it, no strings attached :-)

**Comment by ErikSchierboom** [comment]
Okay! Sure :)

**Pull request closed without merging**
